# Generated by Django 3.2.8 on 2021-11-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_chunk_upload_handlers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scannedfile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
