name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"]
        # empty string is the same as latest
        django-version: ["==4.2.*", "==5.0.*", ""]

    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: pip install django${{ matrix.django-version }}
      - run: python load_tests.py
      # - run: tox
      #   env:
      #     PYTHON_VERSION: ${{ matrix.python-version }}
